name: Pull Request Testing

# Trigger the workflow on pull requests targeting specific branches
on:
  pull_request:
    branches:
      - main       # Target branch: main
      - dev        # Target branch: dev

jobs:
  test:
    # Specify the type of machine to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up a specific programming language environment (example: Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Lint the code (optional step)
      - name: Run linting
        run: npm run lint
