on: push
name: npm build, lint, test and publish
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
  npmTest:
    name: npm test
    runs-on: ubuntu-latest
    needs: npmInstall
    steps:
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
  npmLint:
    name: npm lint
    runs-on: ubuntu-latest
    needs: npmInstall
    steps:
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
  dockerBuild:
    name: docker build
    runs-on: ubuntu-latest
    needs: [npmTest, npmLint]
    steps:
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t abhinavdhasmana/github-action-example-node .
  dockerPush:
    name: docker login and push
    runs-on: ubuntu-latest
    needs: dockerBuild
    steps:
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push abhinavdhasmana/github-action-example-node
